version: "3"
services:
  ags:
    image: simhnna/silverstrike:dev
    entrypoint: /app/start.sh
    environment:
      - DATABASE_URL=sqlite:////data/db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - ./start.sh:/app/start.sh
      - ./settings_override.py:/app/local_settings.py
      - data:/data
volumes:
  data:
